require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  # The pod's name is the iOS module name from nitro.json, and has to stay that
  # way: the generated bridge imports `PdfSdk-Swift.h`, which is the header
  # Xcode writes for a Swift module of this name.
  s.name         = "PdfSdk"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.description  = package["description"]
  s.homepage     = "https://github.com/Halilibrahimakyz/react-native-pdf-sdk"
  s.license      = { :type => "MIT" }
  s.authors      = "Halil İbrahim Akyüz"
  s.platforms    = { :ios => min_ios_version_supported }
  # Never fetched: the app carries this package inside it and CocoaPods is
  # pointed at the folder. Here because a podspec must name a source.
  s.source       = { :git => "https://github.com/Halilibrahimakyz/react-native-pdf-sdk.git", :tag => "v#{s.version}" }

  s.source_files = ["ios/**/*.{swift,h,m,mm}"]
  # Run on a Mac rather than on a phone; see ios/tests/run.sh.
  s.exclude_files = ["ios/tests/**/*"]

  # Add all files generated by Nitrogen
  load 'nitrogen/generated/ios/PdfSdk+autolinking.rb'
  add_nitrogen_files(s)

  s.dependency "React-jsi"
  s.dependency "React-callinvoker"
  install_modules_dependencies(s)
end
